### ISSUE TITLE
Will the data and source code be uploaded?

### ISSUE THREAD

**Issue by MikeMikeMikeMike** [yohanjo/kenli#1]

**Comment by SpeedOfMagic** [comment]
I contacted Yohan Jo, and he replied on 2022-01-24 that he will publish code "hopefully within 1-2 months".
Moreover, he said that he'll try to upload stuff gradually.

**Comment by yohanjo** [comment]
I'm sorry for the delay. I just uploaded the counterevidence retrieval dataset and annotations. I'll upload other files and code gradually.
